# Generated by Django 5.2 on 2025-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_category_options_alter_dinnerplatters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
